openapi: 3.0.0
servers:
  - description: Securedoc Enterprise Server
    url: api.winmagic.com/api/
    
info:
  description: |
    These are the REST APIs provided by the SecureDoc Enterprise Server
    by [WinMagic Corporation](http://www.winmagic.com). Find out more about WinMagic and it's
    enterprise-grade and endpoint encryption solutions at
    [http://www.winmagic.com](http://www.winmagic.com).
  version: "1.0.0"
  title:  SecureDoc Enterprise Server 
  contact:
    email: contact@winmagic.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
  - name: admin
    description: Admin management APIs
  - name: user
    description: User management APIs

paths:
  /admin/login:
    post:
      tags:
        - admin
      summary: Logs user into the system
      description: Multiple status values can be provided with comma separated strings
      operationId: accountLogin
      parameters:
        - name: userName
          in: query
          description: The admin name for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
            application/xml:
              schema:
                type: string
        '400':
          description: Invalid username/password supplied            
  /admin/logout:
    get:
      tags:
        - admin
      summary: Logs out current logged in system user
      operationId: accountLogout
      responses:
        default:
          description: successful operation
  /admin/password:
    put:
      tags:
        - admin
      summary: Changes the password of the system user
      operationId: accountPasswordChange
      parameters:
        - name: userName
          in: query
          description: login name for the user
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: Password for the user
          required: true
          schema:
            type: string      
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiResponse'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiResponse'
        '400':
          description: Invalid status value
  
  /user/challengeResponse:
    get:
      tags:
        - user
      summary: Retrieves a numeric value that will be used as a Challenge Response
      operationId: accountLogout
      parameters:
        - name: api_key
          in: header
          required: true
          schema:
            type: string      
        - name: userName
          in: query
          description: login name for the user
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: Password for the user
          required: true
          schema:
            type: string      
        - name: secureDocChallenge
          in: query
          description: SecureDoc Challenge
          required: false
          schema:
            type: string
        - name: passwordRecoveryChallenge
          in: query
          description: Password Recovery Challenge
          required: false
          schema:
            type: string               
      responses:
        default:
          description: successful operation
      security:
        - auth_user:
            - 'write:pets'
            - 'read:pets'
components:
  schemas:
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string

  securitySchemes:
    auth_user:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://api.winmagic.com/sts'
          scopes:
            'write:user': modify user information
            'read:user': read user information
    api_key:
      type: apiKey
      name: api_key
      in: header